name: Auto Approve

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve
      uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'imgbot[bot]'
      with:
        github-token: "${{ secrets.GT }}"
    - name: Merge
      uses: "pascalgn/automerge-action@c29cef1b62bfb675777896255a70c69fc01bcfe4"
      with:
        GITHUB_TOKEN: "${{ secrets.GT }}"
        method: 'squash'
        MERGE_FILTER_AUTHOR: 'imgbot[bot]'
